export const ACTION_TYPE = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  ADDPRODUCT: "ADDPRODUCT",
  DELETEPRODUCT: "DELETEPRODUCT",
  INCREMENTPRODUCT: "INCREMENTPRODUCT",
  DECREMENTPRODUCT: "DECREMENTPRODUCT",
  TOTALPRICE: "TOTALPRICE",
  TOTALITEM: "TOTALITEM",
  DELETEITEMFROMCART: "DELETEITEMFROMCART",
  DELETEALLFROMCART: "DELETEALLFROMCART",
  ADDCHECKOUTITEM: "ADDCHECKOUTITEM",
};
